2020-09-07 13:08:03 -- Failed execute_querys (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 253, in execute_querys
    cursorSQL.execute(query)
  File "C:\Miniconda3\envs\arcgispro-py3\lib\site-packages\psycopg2\extras.py", line 248, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

)
2020-09-07 13:08:03 -- Failed format_data (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 267, in format_data
    for row in cursor.fetchall():
AttributeError: 'NoneType' object has no attribute 'fetchall'
)
2020-09-07 13:08:03 -- Failed insert_service (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 136, in insert_service
    if len(data) > 0:
TypeError: object of type 'NoneType' has no len()
)
2020-09-07 13:08:03 -- Failed execute_querys (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 252, in execute_querys
    cursorSQL = conexion.cursor(cursor_factory=RealDictCursor)
psycopg2.InterfaceError: connection already closed
)
2020-09-07 13:08:03 -- Failed format_data (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 267, in format_data
    for row in cursor.fetchall():
AttributeError: 'NoneType' object has no attribute 'fetchall'
)
2020-09-07 13:08:03 -- Failed insert_service (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 136, in insert_service
    if len(data) > 0:
TypeError: object of type 'NoneType' has no len()
)
2020-09-07 13:08:03 -- Failed execute_querys (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 252, in execute_querys
    cursorSQL = conexion.cursor(cursor_factory=RealDictCursor)
psycopg2.InterfaceError: connection already closed
)
2020-09-07 13:08:03 -- Failed format_data (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 267, in format_data
    for row in cursor.fetchall():
AttributeError: 'NoneType' object has no attribute 'fetchall'
)
2020-09-07 13:08:03 -- Failed insert_service (Traceback (most recent call last):
  File "c:/Users/simio/Documents/ESRI Chile/Proyectos/Sernatur/script/main.py", line 136, in insert_service
    if len(data) > 0:
TypeError: object of type 'NoneType' has no len()
)
